"""
Adversary agent node.

Takes the generator's initial answer and uses Groq to produce a structured
critique identifying weaknesses, unsupported claims, and contradictions.
"""

import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq

load_dotenv()

_llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0.4,
)

SYSTEM_PROMPT = (
    "You are a rigorous fact-checking adversary. Your job is to critically examine "
    "an answer generated by an AI system and produce a structured critique.\n\n"
    "Your critique MUST include the following sections:\n"
    "1. **Weaknesses** — logical gaps, vague language, or shallow reasoning.\n"
    "2. **Unsupported Claims** — statements not backed by the cited chunks.\n"
    "3. **Contradictions** — internal inconsistencies or conflicts with the source chunks.\n\n"
    "Be specific and reference exact phrases from the answer. If the answer is "
    "genuinely strong, say so and explain why."
)


def adversary_node(state: dict) -> dict:
    """Critique the initial answer for weaknesses and errors."""
    initial_answer: str = state.get("initial_answer", "")
    chunks: list[str] = state.get("chunks", [])

    chunks_text = "\n\n".join(
        f"[Chunk {i + 1}]: {chunk}" for i, chunk in enumerate(chunks)
    )

    user_message = (
        f"Source Chunks:\n{chunks_text}\n\n"
        f"Answer to critique:\n{initial_answer}\n\n"
        "Provide your structured critique."
    )

    response = _llm.invoke(
        [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ]
    )

    return {"critique": response.content}
